declare module 'vue' {
  export interface GlobalComponents {
    XAlert: typeof import('@jetstreamlabs/zen')['XAlert']
    XAvatar: typeof import('@jetstreamlabs/zen')['XAvatar']
    XBadge: typeof import('@jetstreamlabs/zen')['XBadge']
    XBreadcrumbs: typeof import('@jetstreamlabs/zen')['XBreadcrumbs']
    XButton: typeof import('@jetstreamlabs/zen')['XButton']
    XButtonGroup: typeof import('@jetstreamlabs/zen')['XButtonGroup']
    XCard: typeof import('@jetstreamlabs/zen')['XCard']
    XCheckbox: typeof import('@jetstreamlabs/zen')['XCheckbox']
    XCollapse: typeof import('@jetstreamlabs/zen')['XCollapse']
    XContainer: typeof import('@jetstreamlabs/zen')['XContainer']
    XDivider: typeof import('@jetstreamlabs/zen')['XDivider']
    XDrawer: typeof import('@jetstreamlabs/zen')['XDrawer']
    XForm: typeof import('@jetstreamlabs/zen')['XForm']
    XIcon: typeof import('@jetstreamlabs/zen')['XIcon']
    XImage: typeof import('@jetstreamlabs/zen')['XImage']
    XAbac: typeof import('@jetstreamlabs/zen')['XAbac']
    XInput: typeof import('@jetstreamlabs/zen')['XInput']
    XLink: typeof import('@jetstreamlabs/zen')['XLink']
    XMenu: typeof import('@jetstreamlabs/zen')['XMenu']
    XMenuItem: typeof import('@jetstreamlabs/zen')['XMenuItem']
    XModal: typeof import('@jetstreamlabs/zen')['XModal']
    XNotifications: typeof import('@jetstreamlabs/zen')['XNotifications']
    XPagination: typeof import('@jetstreamlabs/zen')['XPagination']
    XPaginationItem: typeof import('@jetstreamlabs/zen')['XPaginationItem']
    XPopover: typeof import('@jetstreamlabs/zen')['XPopover']
    XPopoverContainer: typeof import('@jetstreamlabs/zen')['XPopoverContainer']
    XProgress: typeof import('@jetstreamlabs/zen')['XProgress']
    XRadio: typeof import('@jetstreamlabs/zen')['XRadio']
    XScroll: typeof import('@jetstreamlabs/zen')['XScroll']
    XSelect: typeof import('@jetstreamlabs/zen')['XSelect']
    XSkeleton: typeof import('@jetstreamlabs/zen')['XSkeleton']
    XSlider: typeof import('@jetstreamlabs/zen')['XSlider']
    XSpacer: typeof import('@jetstreamlabs/zen')['XSpacer']
    XSpinner: typeof import('@jetstreamlabs/zen')['XSpinner']
    XTable: typeof import('@jetstreamlabs/zen')['XTable']
    XTableBody: typeof import('@jetstreamlabs/zen')['XTableBody']
    XTableCell: typeof import('@jetstreamlabs/zen')['XTableCell']
    XTableHead: typeof import('@jetstreamlabs/zen')['XTableHead']
    XTableHeader: typeof import('@jetstreamlabs/zen')['XTableHeader']
    XTableRow: typeof import('@jetstreamlabs/zen')['XTableRow']
    XTab: typeof import('@jetstreamlabs/zen')['XTab']
    XTabGroup: typeof import('@jetstreamlabs/zen')['XTabGroup']
    XTag: typeof import('@jetstreamlabs/zen')['XTag']
    XTextarea: typeof import('@jetstreamlabs/zen')['XTextarea']
    XToggle: typeof import('@jetstreamlabs/zen')['XToggle']
    XTooltip: typeof import('@jetstreamlabs/zen')['XTooltip']
    [key: string]: any
  }
}

export {}
